#server.ssl.key-store=classpath:keystore/keystore.p12
#server.ssl.key-store-password=123
#server.ssl.key-password=123
server.ssl.enabled=true
server.ssl.bundle=server-ssl-bundle
spring.ssl.bundle.pem.server-ssl-bundle.keystore.certificate=/etc/letsencrypt/live/3dclinic-api.uz/fullchain.pem
spring.ssl.bundle.pem.server-ssl-bundle.keystore.private-key=/etc/letsencrypt/live/3dclinic-api.uz/privkey.pem
server.tomcat.connection-timeout=5s

logging.file.name=/root/dental/logs-prod/dental-prod.log
spring.datasource.url=jdbc:postgresql://dental-db.uz:5432/dental_db
spring.datasource.username=dental
spring.datasource.password=d3dental
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.Dialect='org.hibernate.dialect.PostgresSQL92Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.hibernate.ddl-auto=update
file.store.path = /root/dental/uploads/

#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false
#springdoc.show-actuator=false